#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
import socket
import threading
import queue
import time
import re  # 【新增】引入正则表达式库，用于提取电压电流

# 引入 ROS 2 的标准消息类型
from std_msgs.msg import String
from geometry_msgs.msg import Point

class DataReceiverNode(Node):
    def __init__(self):
        super().__init__('data_receiver_node')
        
        # 必须把状态变量放在最前面，防止后面的线程启动时找不到该变量而崩溃！
        self.is_running = True
        self.server_socket = None
        # ABB is the TCP client, therefore all outbound robot data must reuse
        # the accepted socket owned by this node. A second ROS node must not
        # bind the same listen address/port.
        self.abb_connection = None
        self.abb_connection_lock = threading.Lock()
        self.abb_tx_queue = queue.Queue(maxsize=100)

        # 1. 网络配置 (ABB 机器人端)。默认值与用户最新版一致。
        self.host = self.declare_parameter(
            'listen_host', '192.168.125.2').value
        self.port = int(self.declare_parameter('listen_port', 45000).value)
        self.target_ip = self.declare_parameter(
            'abb_allowed_ip', '192.168.125.1').value
        
        # 2. TCP 异步可靠转发配置 (发给第三方设备)
        self.forward_ip = self.declare_parameter(
            'forward_ip', '192.168.125.5').value
        self.forward_port = int(
            self.declare_parameter('forward_port', 50000).value)
        self.forward_queue_size = int(
            self.declare_parameter('forward_queue_size', 500).value)
        if not self.host or not self.target_ip or not self.forward_ip:
            raise ValueError('listen/ABB/forward IP parameters must be non-empty')
        if not 1 <= self.port <= 65535 or not 1 <= self.forward_port <= 65535:
            raise ValueError('TCP ports must be within [1, 65535]')
        if self.forward_queue_size <= 0:
            raise ValueError('forward_queue_size must be > 0')
        
        # 创建容量为 500 的消息队列（缓冲池），存放原始字节流
        self.forward_queue = queue.Queue(maxsize=self.forward_queue_size)
        
        # 3. 启动专门的后台 TCP 转发子线程
        self.forward_thread = threading.Thread(target=self.tcp_forwarder_loop)
        self.forward_thread.daemon = True
        self.forward_thread.start()
        
        # 4. 创建 ROS 2 发布者 (Publishers) 
        self.point_pub = self.create_publisher(Point, '/abb/weld_point', 10)
        self.raw_text_pub = self.create_publisher(String, '/abb/raw_text', 10) 
        self.abb_tx_status_pub = self.create_publisher(
            String, '/abb/tx_status', 10)
        self.abb_tx_sub = self.create_subscription(
            String, '/abb/tx_text', self.abb_tx_callback, 10)
        
        # =================【新增：订阅底层焊机状态】=================
        self.weld_status_sub = self.create_subscription(
            String,
            '/weld/status',
            self.weld_status_callback,
            10
        )
        # ============================================================

        # 5. 启动 ABB 接收主线程
        self.receive_thread = threading.Thread(target=self.tcp_server_loop)
        self.receive_thread.daemon = True
        self.receive_thread.start()
        self.abb_sender_thread = threading.Thread(target=self.abb_sender_loop)
        self.abb_sender_thread.daemon = True
        self.abb_sender_thread.start()
        
        self.get_logger().info(f"ABB 数据接收节点已启动，纯文本模式监听: {self.host}:{self.port} ...")
        self.get_logger().info(f"🛡️ 【高可靠转发已开启】ABB 坐标与焊机实时电流电压将转发至 {self.forward_ip}:{self.forward_port}")

    def weld_status_callback(self, msg):
        """【修改】精准提取 RX 接收端的 6 字节原始帧，绝不误抓 TX 发送帧"""
        text = msg.data
        
        # 【关键修复】使用更严格的正则表达式，只匹配 "[<- RX 接收" 之后的 "原始帧:"
        rx_match = re.search(r'\[<-\s*RX.*?原始帧:\s*([0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2})', text)
        
        if rx_match:
            hex_str = rx_match.group(1) 
            
            # 将提取到的真实反馈帧 (例如 "01 00 00 00 00 00") 转换为 6 字节纯二进制
            raw_bytes = bytes.fromhex(hex_str)
            
            try:
                # 放入队列，TCP 转发线程会发给 125.5
                self.forward_queue.put_nowait(raw_bytes)
            except queue.Full:
                pass

    def abb_tx_callback(self, msg):
        """Queue newline-framed ASCII generated by the ABB bridge."""
        if not msg.data:
            return
        try:
            self.abb_tx_queue.put_nowait(msg.data.encode('ascii'))
        except UnicodeEncodeError:
            self.publish_abb_tx_status(False, 'outbound ABB text must be ASCII')
        except queue.Full:
            self.publish_abb_tx_status(False, 'ABB transmit queue is full')

    def publish_abb_tx_status(self, success, message):
        status = String()
        status.data = ('OK:' if success else 'ERROR:') + message
        self.abb_tx_status_pub.publish(status)

    def abb_sender_loop(self):
        """Send queued trajectories over the already accepted ABB socket."""
        while rclpy.ok() and self.is_running:
            try:
                payload = self.abb_tx_queue.get(timeout=1.0)
            except queue.Empty:
                continue
            with self.abb_connection_lock:
                connection = self.abb_connection
            if connection is None:
                self.publish_abb_tx_status(
                    False, 'ABB is disconnected; outbound message was dropped')
                continue
            try:
                connection.sendall(payload)
                self.publish_abb_tx_status(
                    True, f'sent {len(payload)} bytes to ABB')
            except (OSError, socket.error) as exc:
                self.publish_abb_tx_status(False, f'ABB send failed: {exc}')

    def process_received_text(self, text_data):
        """处理接收到的纯文本数据，打印并发布给 ROS"""
        
        clean_text = text_data.strip()
        if not clean_text:
            return
            
        self.get_logger().info(f"[接收文本] {clean_text}")
        
        # 发布原始文本记录，大脑节点 (weld_logic_node) 会继续从这里监听指令
        raw_msg = String()
        raw_msg.data = clean_text
        self.raw_text_pub.publish(raw_msg)
        
        # 按行分割数据，防止粘包时一条消息里有多行
        messages = clean_text.split('\n')
        
        for msg in messages:
            msg = msg.strip()
            if not msg:
                continue
                
            try:
                # 解析类似 P1:538.91,211.97... 的格式
                if msg.startswith('P') and ':' in msg:
                    parts = msg.split(':')
                    coord_part = parts[1]  
                    
                    coords = coord_part.split(',')
                    # 兼容新版的四元数格式，只提取前三个 X, Y, Z 作为轨迹点
                    if len(coords) >= 3:
                        x = float(coords[0])
                        y = float(coords[1])
                        z = float(coords[2])
                        
                        point_msg = Point()
                        point_msg.x = x
                        point_msg.y = y
                        point_msg.z = z
                        self.point_pub.publish(point_msg)
                        
            except Exception as e:
                self.get_logger().error(f"解析失败: {msg}, 错误: {e}")

    def tcp_server_loop(self):
        """主接收循环：接收 ABB 数据，存入队列并解析"""
        try:
            self.server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            self.server_socket.bind((self.host, self.port))
            self.server_socket.listen(1)
            self.server_socket.settimeout(1.0)
            
            while rclpy.ok() and self.is_running:
                try:
                    conn, addr = self.server_socket.accept()
                    client_ip = addr[0]
                    
                    if client_ip == self.target_ip:
                        self.get_logger().info(f"🚀 成功连接到 ABB 机器人: {client_ip}:{addr[1]}")
                        conn.settimeout(1.0)
                        conn.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
                        with self.abb_connection_lock:
                            self.abb_connection = conn
                        
                        while rclpy.ok() and self.is_running:
                            try:
                                data = conn.recv(4096)
                                if not data:
                                    self.get_logger().warn("ABB 机器人已断开连接。")
                                    break
                                
                                # 轨道1：把原汁原味的二进制字节流扔进队列
                                try:
                                    self.forward_queue.put_nowait(data)
                                except queue.Full:
                                    pass 
                                
                                # 轨道2：解码为字符串，交给 ROS 节点内部处理
                                text_data = data.decode('ascii', errors='ignore')
                                self.process_received_text(text_data)
                                
                            except socket.timeout:
                                continue
                            except Exception as e:
                                self.get_logger().error(f"接收异常: {e}")
                                break
                    else:
                        self.get_logger().warn(f"拒绝非法 IP 连接: {client_ip}")
                    with self.abb_connection_lock:
                        if self.abb_connection is conn:
                            self.abb_connection = None
                    conn.close()
                except socket.timeout:
                    pass
        except Exception as e:
            self.get_logger().error(f"Socket 启动失败: {e}")
        finally:
            if self.server_socket:
                self.server_socket.close()

    def tcp_forwarder_loop(self):
        """后台独立转发线程：从队列取数据并通过 TCP 发送给 125.5"""
        forward_sock = None
        
        while rclpy.ok() and self.is_running:
            try:
                # 1. 自动连接 125.5 设备
                if forward_sock is None:
                    forward_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                    
                    # 【本次新增】：禁用 Nagle 算法，实现真正意义上的 0 延迟，发 1 个字节也瞬间发出去！
                    forward_sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
                    
                    forward_sock.settimeout(2.0)
                    try:
                        forward_sock.connect((self.forward_ip, self.forward_port))
                        self.get_logger().info(f"✅ TCP 转发已成功连接至第三方设备 {self.forward_ip}:{self.forward_port}")
                    except Exception:
                        forward_sock.close()
                        forward_sock = None
                        time.sleep(2.0) # 如果连不上，默默等 2 秒再重连
                        continue
                
                # 2. 如果已经连上，就从缓冲池里拿数据发过去
                try:
                    data_to_send = self.forward_queue.get(timeout=1.0)
                    forward_sock.sendall(data_to_send)
                except queue.Empty:
                    pass 
                except Exception as e:
                    self.get_logger().warn(f"⚠️ 发送至 {self.forward_ip} 失败，连接可能已断开: {e}")
                    forward_sock.close()
                    forward_sock = None

            except Exception:
                time.sleep(1.0)
        
        if forward_sock:
            forward_sock.close()

    def destroy_node(self):
        self.is_running = False
        with self.abb_connection_lock:
            connection = self.abb_connection
            self.abb_connection = None
        if connection:
            try:
                connection.shutdown(socket.SHUT_RDWR)
                connection.close()
            except OSError:
                pass
        if self.server_socket:
            self.server_socket.close()
        super().destroy_node()

def main(args=None):
    rclpy.init(args=args)
    node = DataReceiverNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info("节点被手动终止")
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()

if __name__ == '__main__':
    main()
